# -*- coding: utf-8 -*-
"""API-FLASK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ihWo0Gq39B3kVBmViWE7Ja4DVUC0OMtS
"""

!pip install flask_ngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as r

app = Flask(__name__)
run_with_ngrok(app)

data = {
        'Mahesh': {"number": 1, "name": "Mahesh", "age": 25, "city": "Bengalore", "country": "India"},
        'Alex': {"number": 2, "name": "Alex", "age": 26, "city": "London", "country": "UK"},
        'David': {"number": 3, "name": "David", "age": 27, "city": "San Francisco", "country": "USA"},
        'John': {"number": 4, "name": "John", "age": 28, "city": "Toronto", "country": "Canada"},
        'Chris': {"number": 5, "name": "Chris", "age": 29, "city": "Paris", "country": "France"}
    }

@app.route("/")
def home_page():
    return "<marquee><h3> TO CHECK IN PUT ADD '/input' TO THE URL AND TO CHECK OUT PUT ADD '/output' TO THE URL.</h3></marquee>"

@app.route("/input")

def input():
    return jsonify(data)

@app.route('/output', methods=['GET', 'POST'])

def predJson():
    pred = r.choice(["positivo", "negative"])
    nd = data
    nd["prediction"] = pred
    return jsonify(nd)

app.run()